/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const shipment_Logic_Dhl = require('./code/shipment-logic-dhl');

class trackingnumber_crSrv extends LCAPApplicationService {
    async init() {

        this.before('CREATE', 'Shipment', async (request) => {
            await shipment_Logic_Dhl(request);
        });

        return super.init();
    }
}


module.exports = {
    trackingnumber_crSrv
};